# Generated by Django 3.1.7 on 2021-03-11 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=20)),
                ('Confirmed', models.BigIntegerField(max_length=10)),
                ('Deaths', models.BigIntegerField(max_length=10)),
                ('Recovered', models.BigIntegerField(max_length=10)),
                ('Active', models.BigIntegerField(max_length=10)),
                ('New_cases', models.BigIntegerField(max_length=10)),
                ('New_deaths', models.BigIntegerField(max_length=10)),
                ('New_recovered', models.BigIntegerField(max_length=10)),
                ('Deaths_percentage', models.BigIntegerField(max_length=10)),
                ('Recovered_percentage', models.BigIntegerField(max_length=10)),
                ('Region', models.CharField(max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datasource')),
            ],
        ),
    ]
